# Generated by Django 2.1.5 on 2019-01-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unqKey', models.TextField()),
                ('quest', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='messge_bx',
        ),
        migrations.AddField(
            model_name='users',
            name='unqKey',
            field=models.TextField(default='sad'),
            preserve_default=False,
        ),
    ]
