# Generated by Django 2.1.5 on 2019-01-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190124_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='quest',
            new_name='cde',
        ),
    ]
