# Generated by Django 2.1.5 on 2019-01-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190125_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actve',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
