# Generated by Django 2.1.5 on 2019-01-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_project_nme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actve',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cde',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='nme',
            field=models.TextField(blank=True),
        ),
    ]
