# Generated by Django 2.1.5 on 2019-01-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190125_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='usrnme',
        ),
    ]
