# Generated by Django 2.1.5 on 2019-01-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190125_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='unqKey',
            field=models.TextField(default=''),
        ),
    ]
