# Generated by Django 2.1.5 on 2019-01-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190125_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='unqKey',
            field=models.TextField(blank=True, default=''),
        ),
    ]
