# Generated by Django 2.1.5 on 2019-01-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190125_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='LstUsd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte', models.DateTimeField(auto_now_add=True)),
                ('unqKey', models.TextField(blank=True, default='')),
            ],
        ),
    ]
